### ISSUE TITLE
group creation makes user start over if failed 

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-portal#35]
![failedgroupbug](https://user-images.githubusercontent.com/2164180/56803717-4571c380-681b-11e9-80b9-188d4c1829e7.png)

if a user tries to create a group with, say, all capital letters in the name (not clear that this is disallowed), we just get kicked back to the New Group page and have to fill everything out again

maybe we can have an input validator with js or something that prevents the user from continuing with bad input?

**Comment by jarofmy** [comment]
restricting capital letters is apparently a requirement from kubernetes' end, as they want to treat everything as a DNS name. i've restricted the input validator to prevent users from entering bad input
