### ISSUE TITLE
cannot create groups with international calling codes 

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-portal#36]
e.g., in the UK folks use +44 in their phone number, similar with other international numbers. we need better validation since we can only accept 10 digit values currently

**Comment by LincolnBryant** [comment]
https://www.npmjs.com/package/libphonenumber-js perhaps?

**Comment by jarofmy** [comment]
created country coded dropdown menu to select +###, removed limit on digit length. from here, the website/form will take whatever user decides to input, with option to edit afterwards
