### ISSUE TITLE
Show User ID in Profile

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-portal#77]
It would be handy, particularly for helping when users get confused and make multiple accounts, if the user's SLATE ID were displayed o the Profile page, so that they could report it to us when necessary.

**Comment by jarofmy** [comment]
User SLATE ID's are now displayed on the user's Profile page card

**Comment by shawnjuan51** [comment]
I don't know why ur messaging me but I assume the hacker I have or
developer who'd been messing with my privacy is to blame. Please close the
account please I will send my pic with me in it to prove my identity.

mimmers
