### ISSUE TITLE
Create Profile page shows sidebar links, even though they do not work correctly

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-portal#78]
When signing up, I find that the Create Profile page has the full set of sidebar links. However, since my account is not yet created, they don't generally work correctly (fail with HTTP error 500, or the page structure loads but then AJAX requests fail). I think it would be better not to display these links to users who do not yet have an account.

**Comment by jarofmy** [comment]
Both dashboard and sidenavs are now hidden until after user creation has been submitted
